/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazVisual;

import Model.Conex;
import Model.Gladiadores;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlumMati
 */
public class ComercioGladiadores extends javax.swing.JFrame {

    static Connection con = null;
    static Conex pepe = new Conex();
    static ArrayList<Gladiadores> listaGladiadores = new ArrayList<Gladiadores>();
    static DefaultTableModel model = new DefaultTableModel();
    public ComercioGladiadores() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../Img/iconoSpartacus.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        costField = new javax.swing.JTextField();
        vitField = new javax.swing.JTextField();
        strField = new javax.swing.JTextField();
        agiField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        defField = new javax.swing.JTextField();
        backBoton = new javax.swing.JButton();
        buyBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("NAME");

        jLabel3.setText("COST");

        jLabel4.setText("STR");

        jLabel5.setText("VIT");

        jLabel6.setText("AGI");

        strField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strFieldActionPerformed(evt);
            }
        });

        agiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agiFieldActionPerformed(evt);
            }
        });

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane1.setViewportView(descriptionArea);

        jLabel7.setText("DEF");

        defField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vitField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agiField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(defField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(strField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(agiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(defField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 260, 320));

        backBoton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backBoton.setText("GO BACK");
        backBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotonActionPerformed(evt);
            }
        });
        getContentPane().add(backBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 240, 60));

        buyBoton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buyBoton.setText("BUY");
        buyBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBotonActionPerformed(evt);
            }
        });
        getContentPane().add(buyBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 80, 80));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gladiators"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gladiadores.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strFieldActionPerformed
        // TODO add your hafhgfhndling code here:
    }//GEN-LAST:event_strFieldActionPerformed

    private void agiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agiFieldActionPerformed

    private void defFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defFieldActionPerformed

    private void backBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotonActionPerformed
        pepe.CerrarConexion(con);// TODO add your handling code here:
    }//GEN-LAST:event_backBotonActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int row = table.getSelectedRow();
        String tableClick = table.getModel().getValueAt(row, 0).toString();
        
        
        for(int i=0;i<listaGladiadores.size();i++){
    
    if(listaGladiadores.get(i).getNombre().equalsIgnoreCase(tableClick)){
    
    nameField.setText(listaGladiadores.get(i).getNombre());
    costField.setText(String.valueOf(listaGladiadores.get(i).getPrecio()));
    strField.setText(String.valueOf(listaGladiadores.get(i).getFuerza()));
    vitField.setText(String.valueOf(listaGladiadores.get(i).getVitalidad()));
    agiField.setText(String.valueOf(listaGladiadores.get(i).getAgilidad()));
    defField.setText(String.valueOf(listaGladiadores.get(i).getDefensa()));
    descriptionArea.setText(listaGladiadores.get(i).getDescripcion());
    
    
    }
    
    
    
    
    }

    }//GEN-LAST:event_tableMouseClicked

    private void buyBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBotonActionPerformed
        
         int row = table.getSelectedRow();
         
         model.removeRow(row);
         //setear los campos a 0
        
        
        
        
        
        
    }//GEN-LAST:event_buyBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {

            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ComercioGladiadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ComercioGladiadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ComercioGladiadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ComercioGladiadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ComercioGladiadores().setVisible(true);
                }
            });

            // cargo el nombre de todos los gladiadores
            con = pepe.AbrirConexion();
            String query = "Select * from gladiadores where propietario=0";

            PreparedStatement st = con.prepareStatement(query);

            ResultSet rs = st.executeQuery();

            int Id;
            String Nombre;
            String Descripcion;
            int Precio;
            int Victorias;
            int Derrotas;
            int Fuerza;
            int Agilidad;
            int Vitalidad;
            int Defensa;
            int Propietario;

            // llena arraylist de todo el select
            while (rs.next()) {

                Id = rs.getInt("id");
                Nombre = rs.getString("nombre");
                Descripcion = rs.getString("descripcion");
                Precio = rs.getInt("precio");
                Victorias = rs.getInt("victorias");
                Derrotas = rs.getInt("derrotas");
                Fuerza = rs.getInt("fuerza");
                Agilidad = rs.getInt("agilidad");
                Vitalidad = rs.getInt("vitalidad");
                Defensa = rs.getInt("defensa");
                Propietario = rs.getInt("propietario");

                Gladiadores glad = new Gladiadores(Id, Nombre, Descripcion, Precio, Victorias, Derrotas, Fuerza, Agilidad, Vitalidad, Defensa, Propietario);

                listaGladiadores.add(glad);

            }
            pepe.CerrarConexion(con);
            st.close();
            rs.close();
        

            // ahora hago lo de la tabla...
            

            Object datosFila[] = new Object[1];     // 1 porque es una columnas solo

            model = (DefaultTableModel) table.getModel();
            for (int i = 0; i < listaGladiadores.size(); i++) {
                datosFila[0] = listaGladiadores.get(i).getNombre();
                model.addRow(datosFila);

            }

        } catch (SQLException ex) {
            Logger.getLogger(ComercioGladiadores.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agiField;
    private javax.swing.JButton backBoton;
    private javax.swing.JButton buyBoton;
    private javax.swing.JTextField costField;
    private javax.swing.JTextField defField;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField strField;
    private static javax.swing.JTable table;
    private javax.swing.JTextField vitField;
    // End of variables declaration//GEN-END:variables
}
