/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazVisual;

/**
 *
 * @author AlumMati
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonLucha = new javax.swing.JButton();
        botonBuy = new javax.swing.JButton();
        infoGeneral = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lossesField = new javax.swing.JTextField();
        goldField = new javax.swing.JTextField();
        winsField = new javax.swing.JTextField();
        botonSell = new javax.swing.JButton();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonLucha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonLucha.setText("GO ARENA");
        getContentPane().add(botonLucha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 630, 80));

        botonBuy.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonBuy.setText("Sell Gladiators");
        getContentPane().add(botonBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 170, 40));

        infoGeneral.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        infoGeneral.setForeground(new java.awt.Color(255, 255, 255));
        infoGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoGeneral.setText("ACCOUNT STATS");
        getContentPane().add(infoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 160, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WINS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 40, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOSSES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 50, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GOLD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 50, 30));

        lossesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lossesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 110, 30));

        goldField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldFieldActionPerformed(evt);
            }
        });
        getContentPane().add(goldField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 110, 30));
        getContentPane().add(winsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 110, 30));

        botonSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonSell.setText("Buy Gladiators");
        getContentPane().add(botonSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 170, 40));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menuPrincipal.jpg"))); // NOI18N
        getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 831, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lossesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lossesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lossesFieldActionPerformed

    private void goldFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuy;
    private javax.swing.JButton botonLucha;
    private javax.swing.JButton botonSell;
    private javax.swing.JTextField goldField;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel infoGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lossesField;
    private javax.swing.JTextField winsField;
    // End of variables declaration//GEN-END:variables
}
