/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazVisual;

import Model.Usuario;
import javax.swing.ImageIcon;

/**
 *
 * @author AlumMati
 */
public class MenuUsuario extends javax.swing.JFrame {

    static Usuario user = null;
    
    /**
     * Creates new form MenuPrincipal
     */
    /*public MenuUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage (new ImageIcon(getClass().getResource("../Img/iconoSpartacus.jpg")).getImage());
    }*/
    
     public MenuUsuario(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage (new ImageIcon(getClass().getResource("../Img/iconoSpartacus.jpg")).getImage());
        this.user = user;
        poneCosas();
        //winsField.setText(String.valueOf(user.getVictorias()));
        //lossesField.setText(String.valueOf(user.getDerrotas()));
        //ratioField.setText(String.valueOf(user.getRatio()));
        //goldField.setText(String.valueOf(user.getSaldo()));
    }
     
     public void poneCosas(){
        winsField.setText(String.valueOf(user.getVictorias()));
        lossesField.setText(String.valueOf(user.getDerrotas()));
        ratioField.setText(String.valueOf(user.getRatio()));
        goldField.setText(String.valueOf(user.getSaldo()));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonLucha = new javax.swing.JButton();
        infoGeneral = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lossesField = new javax.swing.JTextField();
        ratioField = new javax.swing.JTextField();
        winsField = new javax.swing.JTextField();
        botonBuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        goldField = new javax.swing.JTextField();
        botonExit = new javax.swing.JButton();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonLucha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonLucha.setText("GO ARENA");
        botonLucha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLuchaActionPerformed(evt);
            }
        });
        getContentPane().add(botonLucha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 530, 80));

        infoGeneral.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        infoGeneral.setForeground(new java.awt.Color(255, 255, 255));
        infoGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoGeneral.setText("ACCOUNT STATS");
        getContentPane().add(infoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 160, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WINS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 40, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOSSES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 50, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RATIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 50, 30));

        lossesField.setEditable(false);
        lossesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lossesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 110, 30));

        ratioField.setEditable(false);
        ratioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratioFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ratioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 110, 30));

        winsField.setEditable(false);
        getContentPane().add(winsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 110, 30));

        botonBuy.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonBuy.setText("Buy Gladiators");
        botonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuyActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 170, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GOLD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 50, 30));

        goldField.setEditable(false);
        goldField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldFieldActionPerformed(evt);
            }
        });
        getContentPane().add(goldField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 110, 30));

        botonExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonExit.setText("EXIT");
        botonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExitActionPerformed(evt);
            }
        });
        getContentPane().add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 80, 40));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menuPrincipal.jpg"))); // NOI18N
        getContentPane().add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lossesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lossesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lossesFieldActionPerformed

    private void ratioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratioFieldActionPerformed

    private void botonLuchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLuchaActionPerformed
        
        
        SeleccionGladiador random = new SeleccionGladiador(user);
        this.setVisible(false);
        random.setVisible(true);
        
        
        
    }//GEN-LAST:event_botonLuchaActionPerformed

    private void goldFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldFieldActionPerformed

    private void botonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuyActionPerformed
        ComercioGladiadores random = new ComercioGladiadores(user);
        this.setVisible(false);
        random.setVisible(true);
        
    }//GEN-LAST:event_botonBuyActionPerformed

    private void botonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_botonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //OJO AQUI HE PUESTO USER NO SE SI ESTARÁ BIEN
                new MenuUsuario(user).setVisible(true);
                System.out.println("hehehe");
            }
        });
            System.out.println("hola");
        
        System.out.println("adios");
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuy;
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonLucha;
    private static javax.swing.JTextField goldField;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel infoGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JTextField lossesField;
    private static javax.swing.JTextField ratioField;
    private static javax.swing.JTextField winsField;
    // End of variables declaration//GEN-END:variables
}
